;    include-65: Include files for 6502 and related processors, generic and Commodore 64.
;    Copyright (C) 2022  C64PECTRE
;
;    This program is free software: you can redistribute it and/or modify
;    it under the terms of the GNU General Public License as published by
;    the Free Software Foundation, either version 3 of the License, or
;    (at your option) any later version.
;
;    This program is distributed in the hope that it will be useful,
;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;    GNU General Public License for more details.
;
;    You should have received a copy of the GNU General Public License
;    along with this program.  If not, see <https://www.gnu.org/licenses/>.
;
;    Contact: https://github.com/c64pectre/include-65/ create an issue

;;; summary: Colors

COLOR_BLK = $0  ;  0 black               rgb:#000000 CTRL+1 PETSCII_BLACK
COLOR_WHT = $1  ;  1 white               rgb:#FFFFFF CTRL+2 PETSCII_WHITE
COLOR_RED = $2  ;  2 red                 rgb:#880000 CTRL+3 PETSCII_RED
COLOR_CYN = $3  ;  3 cyan                rgb:#AAFFEE CTRL+4 PETSCII_CYAN
COLOR_PUR = $4  ;  4 purple              rgb:#CC44CC CTRL+5 PETSCII_PURPLE
COLOR_GRN = $5  ;  5 green               rgb:#00CC55 CTRL+6 PETSCII_GREEN
COLOR_BLU = $6  ;  6 blue                rgb:#0000AA CTRL+7 PETSCII_BLUE
COLOR_YEL = $7  ;  7 yellow              rgb:#EEEE77 CTRL+8 PETSCII_YELLOW
COLOR_ORA = $8  ;  8 orange              rgb:#DD8855 CBM+1  PETSCII_ORANGE
COLOR_BRO = $9  ;  9 brown               rgb:#664400 CBM+2  PETSCII_BROWN
COLOR_LRD = $A  ; 10 light red (or pink) rgb:#FF7777 CBM+3  PETSCII_LIGHT_RED
COLOR_DGY = $B  ; 11 dark gray           rgb:#333333 CBM+4  PETSCII_DARK_GRAY
COLOR_GRY = $C  ; 12 (medium) gray       rgb:#777777 CBM+5  PETSCII_MEDIUM_GRAY
COLOR_LGN = $D  ; 13 light green         rgb:#AAFF66 CBM+6  PETSCII_LIGHT_GREEN
COLOR_LBL = $E  ; 14 light blue          rgb:#0088FF CBM+7  PETSCII_LIGHT_BLUE
COLOR_LGY = $F  ; 15 light gray          rgb:#BBBBBB CBM+8  PETSCII_LIGHT_GRAY
